### PR TITLE
Update swag.md

### PR DESCRIPTION
**Pull request by CeliGaroe**
WordCamp Central does not accept swag back anymore.

### CODE REVIEW

**Comment by LittleBigThing** [comment]
Looks good to me! :-)

**Comment by noraferreiros** [comment]
If I have understood it correctly, you can ask WordPress Central to help you on coordinating with other WordCamps to send the landyards. I mean: organizers wouldn't have to directly contact other organizers, but ask WordPress Central to do so. I've take the info from another person and, as I have never been a WordCamp organizer myself, I'm not sure about this. My point is, I'm not sure about this sentence because it seems organizers have to manage it by themselves. I propose something like: "When possible, coordinate with other WordPress Events organizers to share usable swag. You can ask WordCamp Central for help in managing this if needed."

**Comment by CeliGaroe** [comment]
Ok. I didn't know WordCamp Central could put you in contact with other organizers like that, so being that way, your phrasing makes more sense. Do you want me to include it myself in the pull request or do you want to make the change yourself, @noraferreiros?

**Review by lironmil — APPROVED** [review]
@CeliGaroe - looks good, thank you.

**Pull request merged**
