### PR TITLE
Delete assets directory

### PR DESCRIPTION
**Pull request by mukeshpanchal27**

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
@CeliGaroe @LittleBigThing could you please review. Thanks!

**Comment by CeliGaroe** [comment]
@javiercasares Hi Javi! You were the one who created this directory, should we delete it or it has a purpose beyond my knowledge? Thanks!

**Comment by javiercasares** [comment]
The idea behind the `assets` directory is to add images or any other document that will be on the site Media, as many other handbooks have.

**Comment by CeliGaroe** [comment]
> The idea behind the `assets` directory is to add images or any other document that will be on the site Media, as many other handbooks have.

In that case, I understand we should not delete this directory. Thank you for the explanation, @javiercasares.

**Comment by LittleBigThing** [comment]
Thanks @mukeshpanchal27.
Closing this based on the comments above. I think it is OK to have the directory available for when we need it (and now we know why it is there).

**Pull request closed without merging**
